# Generated by Django 4.2.3 on 2023-07-12 10:51

from django.db import migrations, models
import file_downloader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('html_file', models.FileField(upload_to='uploads/', validators=[file_downloader.models.validate_html_file_extension])),
                ('css_file', models.FileField(upload_to='uploads/', validators=[file_downloader.models.validate_css_file_extension])),
            ],
        ),
    ]
